In [2]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

/home/arabi/anaconda3/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [3]:
data = pd.read_csv("not_enough_credit_JIF_15.csv")

In [3]:
glm_bet = data[data.hits < data.glam]
hit_bet = data[data.hits > data.glam]
ga = glm_bet[glm_bet.asi > 0.50]
gb = glm_bet[glm_bet.black > 0.50]
gw = glm_bet[glm_bet.white > 0.50]
ha = hit_bet[hit_bet.asi > 0.50]
hb = hit_bet[hit_bet.black > 0.50]
hw = hit_bet[hit_bet.white > 0.50]
gh = glm_bet[glm_bet.his > 0.50]
hh = hit_bet[hit_bet.his > 0.50]
print(len(ga)," ",len(gb),' ',len(gw)," ",len(gh)," ",len(ha)," ",len(hb)," ",len(hw)," ",len(hh))
table = [[len(ga),len(gb),len(gw),len(gh)],[len(ha),len(hb),len(hw),len(hh)]]
stat, p, dof, expected = chi2_contingency(table)
print("statistics ",stat," p val ",p," dof ",dof," expected ",expected)

495   16   1687   65   5244   319   25713   1051
statistics  50.026233795761  p val  7.887060421743808e-11  dof  3  expected  [[3.75465655e+02 2.19168835e+01 1.79260480e+03 7.30126626e+01]
 [5.36353435e+03 3.13083117e+02 2.56073952e+04 1.04298734e+03]]


In [4]:
glm_bet = data[data.hits < data.glam]
hit_bet = data[data.hits > data.glam]

glm_bet = glm_bet.dropna(subset=['female','male'])
gender = ["Female" if glm_bet['female'][ind] > glm_bet['male'][ind] else "Male" for ind in glm_bet.index]
glm_bet['gender'] = gender
gm = glm_bet[glm_bet.gender == "Male"]
gf = glm_bet[glm_bet.gender == "Female"]


hit_bet = hit_bet.dropna(subset=['female','male'])
gender = ["Female" if hit_bet['female'][ind] > hit_bet['male'][ind] else "Male" for ind in hit_bet.index]
hit_bet['gender'] = gender
hm = hit_bet[hit_bet.gender == "Male"]
hf = hit_bet[hit_bet.gender == "Female"]

print(len(gf)," ",len(gm)," ",len(hf)," ",len(hm))
table = [[len(gf),len(gm)],[len(hf),len(hm)]]
stat, p, dof, expected = chi2_contingency(table)
print(stat," ",p," ",dof," ",expected)

592   1351   10909   18017
40.574849102725224   1.8922670956226282e-10   1   [[  723.91211248  1219.08788752]
 [10777.08788752 18148.91211248]]


In [5]:
glm_bet = data[data.hits < data.glam]
hit_bet = data[data.hits > data.glam]
glm_bet['age'] =glm_bet['endyear'] - glm_bet['startyear']
hit_bet['age'] =hit_bet['endyear'] - hit_bet['startyear']
a = len(glm_bet)
b = len(hit_bet)


glm_bet_early = glm_bet[glm_bet.age <= 5]
glm_bet_senior = glm_bet[glm_bet.age > 10]
glm_bet_mid = glm_bet[glm_bet.age <= 10]
glm_bet_mid = glm_bet_mid[glm_bet_mid.age > 5]

ga = len(glm_bet_early)
gb = len(glm_bet_mid)
gc = len(glm_bet_senior)

hit_bet_early = hit_bet[hit_bet.age <= 5]
hit_bet_senior = hit_bet[hit_bet.age > 10]
hit_bet_mid = hit_bet[hit_bet.age <= 10]
hit_bet_mid = hit_bet_mid[hit_bet_mid.age > 5]

ha = len(hit_bet_early)
hb = len(hit_bet_mid)
hc = len(hit_bet_senior)
print(ga," ",gb, " ",gc," ",ha," ",hb," ",hc)
table = [[ga,gb,gc],[ha,hb,hc]]
print("printing results ")
stat, p, dof, expected = chi2_contingency(table)
print(stat," ",p," ",dof," ",expected)

71   201   2026   717   2813   29341
printing results 
8.289669684064467   0.015846052837099087   2   [[   51.48920925   196.93969121  2049.57109955]
 [  736.51079075  2817.06030879 29317.42890045]]


<ipython-input-5-62035ebf4107>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  glm_bet['age'] =glm_bet['endyear'] - glm_bet['startyear']
<ipython-input-5-62035ebf4107>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hit_bet['age'] =hit_bet['endyear'] - hit_bet['startyear']


In [6]:
glm_bet = data[data.hits_rank < data.glam_rank]
hit_bet = data[data.hits_rank > data.glam_rank]
glm_bet['age'] =glm_bet['endyear'] - glm_bet['startyear']
hit_bet['age'] =hit_bet['endyear'] - hit_bet['startyear']
a = len(glm_bet)
b = len(hit_bet)


glm_bet_early = glm_bet[glm_bet.age <= 5]
glm_bet_senior = glm_bet[glm_bet.age > 10]
glm_bet_mid = glm_bet[glm_bet.age <= 10]
glm_bet_mid = glm_bet_mid[glm_bet_mid.age > 5]

ga = len(glm_bet_early)
gb = len(glm_bet_mid)
gc = len(glm_bet_senior)

hit_bet_early = hit_bet[hit_bet.age <= 5]
hit_bet_senior = hit_bet[hit_bet.age > 10]
hit_bet_mid = hit_bet[hit_bet.age <= 10]
hit_bet_mid = hit_bet_mid[hit_bet_mid.age > 5]

ha = len(hit_bet_early)
hb = len(hit_bet_mid)
hc = len(hit_bet_senior)
print(ga," ",gb, " ",gc," ",ha," ",hb," ",hc)
table = [[ga,gb,gc],[ha,hb,hc]]
print("printing results ")
stat, p, dof, expected = chi2_contingency(table)
print(stat," ",p," ",dof," ",expected)

229   866   12943   674   2456   20601
printing results 
258.00479839445   9.439953963858429e-57   2   [[  335.62747227  1234.72255024 12467.64997749]
 [  567.37252773  2087.27744976 21076.35002251]]


<ipython-input-6-91ca26d5f151>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  glm_bet['age'] =glm_bet['endyear'] - glm_bet['startyear']
<ipython-input-6-91ca26d5f151>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hit_bet['age'] =hit_bet['endyear'] - hit_bet['startyear']
